name: Build Windows EXE

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install opencv-python mediapipe scipy numpy sounddevice pyinstaller
      - run: pyinstaller --onefile main.py
      - uses: actions/upload-artifact@v3
        with:
          name: drowsiness_detector_windows
          path: dist/main.exe